on:
  push:
    branches: [ main ]
    paths:
      - 'glue/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file glue/crawler.yaml \
          --stack-name imba-glue-crawler \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset

    - name: Start Crawler (Optional)
      run: |
        aws glue start-crawler --name imba-data-crawler
