steps:
  # 1. CHECKOUT CODE
  - uses: actions/checkout@v2  # Gets your code from GitHub repository

  # 2. AWS CREDENTIALS SETUP
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      # Use GitHub secrets for secure credential storage
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}

  # 3. DEPLOY CLOUDFORMATION
  - name: Deploy CloudFormation stack
    run: |
      aws cloudformation deploy \
        --template-file glue/crawler.yaml \  # Your template file
        --stack-name instacart-glue-crawler \  # Stack name in AWS
        --capabilities CAPABILITY_IAM \  # Allow IAM role creation
        --no-fail-on-empty-changeset  # Don't fail if no changes

  # 4. START CRAWLER (OPTIONAL)
  - name: Start Crawler (Optional)
    run: |
      aws glue start-crawler --name imba-data-crawler