name: Deploy IAM Roles
on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        description: "S3 bucket name for storing Terraform plans"
        required: true
      s3_path:
        description: "S3 path prefix for plans"
        required: true

jobs:
  terraform:
    name: 'Update IAM Resources'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          
      - name: Import and Update Resources
        working-directory: IaC/IAM/Glue_Crawler_Role
        run: |
          # Initialize Terraform
          terraform init
          
          # Import existing role if not in state
          terraform import aws_iam_role.lambda_invocation_role lambda-invocation-role || echo "Role already in state or import failed"
          
          # Create and save plan
          terraform plan -out=tfplan-iam-role
          
          # Store plan in S3
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 cp tfplan-iam-role s3://${{ github.event.inputs.s3_bucket }}/${{ github.event.inputs.s3_path }}/tfplan-iam-role-${TIMESTAMP}
          
          # Apply changes
          terraform apply -auto-approve tfplan-iam-role
